BileMoBundle\Entity\Phone:
    type: entity
    table: null
    repositoryClass: BileMoBundle\Repository\PhoneRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 255
            unique: true
        mark:
            type: string
            length: 255
        systemVersion:
            type: string
            length: 255
        memory:
            type: string
            length: 255
        color:
            type: string
            length: 255
        description:
            type: text
        price:
            type: integer
        quantity:
            type: integer
        created:
            type: datetime
        updated:
            type: datetime
        slug:
            type: string
            length: 255
    lifecycleCallbacks: {  }
